
# Get more detailed logs, and don't write them to file (use stdout instead)
logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: ""

# Turn on devtools in dev
spring:
  devtools.add-properties: true

  # H2 database in file
  datasource:
    url: jdbc:h2:file:./spiis-database
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update # Create missing tables

  # Enable h2 console for database debugging
  h2.console.enabled: true
  h2.console.path: /h2

# Actuator, to be able to shut down the server over HTTP
# https://www.baeldung.com/spring-boot-shutdown
management.endpoints.web.exposure.include: "*"
management.endpoint.shutdown.enabled: true
