
server.port: 8180

spring:
  application.name: SpiisServer

  # Turn off devtool props in prod
  devtools.add-properties: false

  # H2 database in file
  datasource:
    url: jdbc:h2:file:./spiis-database
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    # This is best practice, otherwise we get a warning
    open-in-view: false

    # More h2 stuff
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

logging:
  # Set all log levels to WARN
  level.root: WARN

  # Write the logs to a tmp file
  file.name: "${java.io.tmpdir}/${spring.application.name}.log"


