
server.port: 8180

spring:
  application.name: SpiisServer

  main.banner-mode: "off"

  # Turn off devtool props in prod
  devtools.add-properties: false

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/spiisdb
    username: spiis
    password: spiis-postgres-passwd

  jpa:
    # This is best practise, we use manual @Transactions
    open-in-view: false
    hibernate.ddl-auto: update # Create missing tables

  jackson:
    time-zone: UTC

logging:
  # Set all log levels to WARN
  level.root: WARN
  level.spiis.server.controller: TRACE

  # Write the logs to a tmp file
  file.name: "${java.io.tmpdir}/${spring.application.name}.log"
